# Generated by Django 5.1.7 on 2025-04-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='annonymous', max_length=20),
        ),
    ]
