# Generated by Django 5.1.7 on 2025-04-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='gameinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('genre', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('topurch', models.URLField()),
                ('walk', models.URLField()),
                ('sys_req', models.TextField()),
            ],
        ),
    ]
