# Generated by Django 5.1.7 on 2025-04-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_gameinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfo',
            name='deveoper',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='publisher',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='summary',
            field=models.TextField(default='unknown'),
        ),
    ]
