# Generated by Django 5.1.7 on 2025-04-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_gameinfo_deveoper_gameinfo_publisher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='deveoper',
            new_name='developer',
        ),
    ]
